trigger:
- develop

pool:
  name: Default   # self-hosted agent

steps:
- script: |
    java -version
    echo JAVA_HOME=%JAVA_HOME%
  displayName: 'Verify Java'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean package'
